# Generated by Django 4.0.3 on 2022-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicrama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='how_can_we_help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
