# Generated by Django 4.0.3 on 2022-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicrama', '0002_form_how_can_we_help_alter_form_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('selling_price', models.CharField(max_length=30)),
                ('mrp', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='how_can_we_help',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
