# Generated by Django 4.0.3 on 2022-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicrama', '0003_product_alter_form_email_alter_form_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField(blank=True)),
                ('dob', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('confirm_password', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='how_can_we_help',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
