# Generated by Django 4.0.3 on 2023-02-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicrama', '0004_customer_alter_form_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
